# Generated by Django 5.2.8 on 2026-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="abha_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="id_proof_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="id_proof_type",
            field=models.CharField(
                choices=[
                    ("AADHAAR", "Aadhaar Card"),
                    ("VOTER_ID", "Voter ID"),
                    ("DRIVING_LICENCE", "Driving Licence"),
                    ("PASSPORT", "Passport"),
                ],
                default="AADHAAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_type",
            field=models.CharField(
                choices=[
                    ("OPD", "Outpatient"),
                    ("IPD", "Inpatient"),
                    ("EMERGENCY", "Emergency"),
                    ("REVIEW", "Review"),
                ],
                default="OPD",
                max_length=20,
            ),
        ),
    ]
