# Generated by Django 5.2.8 on 2026-03-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_abha_id_patient_id_proof_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id_proof_number",
            field=models.CharField(
                default="PENDING_ID",
                help_text="Aadhaar or primary ID number",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
