# Generated by Django 5.2.8 on 2026-03-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_id_proof_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_no",
                    models.CharField(
                        help_text="Primary Card Number (e.g., 0001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "aadhar_no",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("mobile_no", models.CharField(max_length=15)),
                ("address", models.TextField()),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_proofs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="card_no",
            field=models.CharField(
                blank=True,
                help_text="Full Card Number (e.g., 0001/2)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_employee_linked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id_proof_type",
            field=models.CharField(
                choices=[
                    ("AADHAAR", "Aadhaar Card"),
                    ("VOTER_ID", "Voter ID"),
                    ("DRIVING_LICENCE", "Driving Licence"),
                    ("PASSPORT", "Passport"),
                    ("EMPLOYEE_CARD", "Employee Card"),
                ],
                default="AADHAAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="employee_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="patients.employeemaster",
            ),
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_no_suffix",
                    models.CharField(help_text="e.g., /1, /2, /3", max_length=10),
                ),
                ("name", models.CharField(max_length=150)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("aadhar_no", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("PRIMARY CARD HOLDER", "Primary Card Holder"),
                            ("SPOUSE", "Spouse"),
                            ("SON", "Son"),
                            ("DAUGHTER", "Daughter"),
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="family_proofs/"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="patients.employeemaster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="family_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="patients.familymember",
            ),
        ),
    ]
