# Generated by Django 5.2.8 on 2026-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_employeemaster_patient_card_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("PRIMARY CARD HOLDER", "Primary Card Holder"),
                    ("SPOUSE", "Spouse"),
                    ("WIFE", "Wife"),
                    ("HUSBAND", "Husband"),
                    ("SON", "Son"),
                    ("DAUGHTER", "Daughter"),
                    ("FATHER", "Father"),
                    ("MOTHER", "Mother"),
                    ("BROTHER", "Brother"),
                    ("SISTER", "Sister"),
                    ("GRANDFATHER", "Grandfather"),
                    ("GRANDMOTHER", "Grandmother"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
