# Generated by Django 5.2.8 on 2026-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_alter_familymember_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
