# Generated by Django 5.2.8 on 2026-03-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_patient_registered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemaster",
            name="additional_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="familymember",
            name="additional_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ProjectFieldConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                ("field_label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("VARCHAR", "Text Field"),
                            ("NUMBER", "Numeric Value"),
                            ("DATE", "Date Picker"),
                        ],
                        default="VARCHAR",
                        max_length=20,
                    ),
                ),
                ("char_length", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="patients.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "field_name")},
            },
        ),
    ]
