# Generated by Django 5.2.8 on 2026-03-28 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_employeemaster_additional_fields_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("coverage", models.CharField(default="WORKSPACE", max_length=100)),
                ("icon", models.CharField(default="Pill", max_length=50)),
                ("color", models.CharField(default="#ec4899", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registry_types",
                        to="patients.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "slug")},
            },
        ),
        migrations.CreateModel(
            name="RegistryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ucode",
                    models.CharField(
                        help_text="Common code/ID for item", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=50)),
                ("additional_fields", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="patients.registrytype",
                    ),
                ),
            ],
            options={
                "unique_together": {("registry_type", "ucode")},
            },
        ),
    ]
