# Generated by Django 5.2.8 on 2026-03-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_registrytype_registrydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("VARCHAR", "Text String"),
                            ("NUMBER", "Numeric Value"),
                            ("DATE", "Date Picker"),
                            ("BOOLEAN", "Toggle (Yes/No)"),
                        ],
                        default="VARCHAR",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "registry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="patients.registrytype",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("registry_type", "slug")},
            },
        ),
    ]
