# Generated by Django 5.2.8 on 2026-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_registryfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="registryfield",
            name="max_length",
            field=models.IntegerField(
                default=255, help_text="Maximum allowed characters/length"
            ),
        ),
    ]
