# Generated by Django 5.2.8 on 2026-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_registryfield_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registryfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("VARCHAR", "VARCHAR"),
                    ("INT", "INT"),
                    ("DATE", "DATE"),
                    ("BOOLEAN", "BOOLEAN"),
                ],
                default="VARCHAR",
                max_length=20,
            ),
        ),
    ]
