# Generated by Django 5.2.8 on 2026-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0013_alter_registryfield_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrytype",
            name="type_category",
            field=models.CharField(
                choices=[
                    ("PERSONNEL_PRIMARY", "Personnel Main Registry"),
                    ("PERSONNEL_DEPENDENT", "Family/Dependent Mapping"),
                    ("CLINICAL_REPOSITORY", "Standard Clinical Data"),
                    ("GENERAL", "Generic Registry"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
    ]
