# Generated by Django 5.2.8 on 2026-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0014_registrytype_type_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="use_registry_for_personnel",
            field=models.BooleanField(
                default=False,
                help_text="Prioritize polymorphic registry for Staff/Family",
            ),
        ),
    ]
