# Generated by Django 6.0.3 on 2026-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_employeemaster_dob_alter_familymember_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
