# Generated by Django 5.2.12 on 2026-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_employeemaster_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Unique Patient ID (e.g., BHSPL0001)', max_length=20, null=True),
        ),
    ]
