# Generated by Django 5.2.12 on 2026-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Unique Patient ID (e.g., BHSPL0001)', max_length=20, null=True, unique=True),
        ),
    ]
