# Generated by Django 5.2.12 on 2026-04-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
    ]
