# Generated by Django 5.2.12 on 2026-04-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_projectlogo_delete_brandinglogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accent_color',
            field=models.CharField(default='#f43f5e', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_color',
            field=models.CharField(default='#a5b4fc', max_length=20),
        ),
    ]
