# Generated by Django 5.2.12 on 2026-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_project_accent_color_project_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_backgrounds/'),
        ),
    ]
