# Generated by Django 5.2.12 on 2026-04-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_project_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background_image',
        ),
    ]
