# Generated by Django 5.2.12 on 2026-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_remove_project_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
