# Generated by Django 5.2.12 on 2026-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_alter_employeemaster_mobile_no_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
