# Generated by Django 5.2.12 on 2026-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_appointments',
            field=models.BooleanField(default=True),
        ),
    ]
