# Generated by Django 5.2.12 on 2026-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_project_allow_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vitals_mandatory',
            field=models.BooleanField(default=True, help_text='Enforce mandatory collection of core vitals (Temp/Weight)'),
        ),
    ]
