# Generated by Django 5.2.12 on 2026-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_project_vitals_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrydata',
            name='aliases',
            field=models.TextField(blank=True, help_text='Comma-separated synonyms or search tags (e.g. Amaryl, Glimepiride)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_color',
            field=models.CharField(default='#1e3a8a', max_length=20),
        ),
    ]
