# Generated by Django 5.2.12 on 2026-05-22 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_registrydata_aliases_alter_project_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='uploaded_sheet.xlsx', max_length=255)),
                ('mode', models.CharField(default='OVERWRITE', max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('success_details', models.JSONField(blank=True, default=list)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='patients.project')),
                ('registry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='patients.registrytype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
