# Generated by Django 5.2.12 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_registryuploadsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryuploadsession',
            name='upload_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
