# Generated by Django 5.2.12 on 2026-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_registryuploadsession_upload_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrydata',
            name='ucode',
            field=models.CharField(help_text='Common code/ID for item', max_length=255),
        ),
    ]
