# Generated by Django 5.2.12 on 2026-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_alter_registrydata_ucode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrytype',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
