# Generated by Django 5.2.12 on 2026-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_registrytype_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='card_no',
            field=models.CharField(help_text='Primary Card Number (e.g., 0001)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employeemaster',
            unique_together={('project', 'aadhar_no'), ('project', 'card_no')},
        ),
    ]
