# Generated by Django 5.2.12 on 2026-06-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_alter_employeemaster_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_custom_visit_date',
            field=models.BooleanField(default=False, help_text="Enables retroactive/late entry protocols for this project's visits."),
        ),
    ]
