# Generated by Django 5.2.12 on 2026-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_project_allow_custom_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this employee is active.'),
        ),
    ]
