# Generated by Django 5.2.12 on 2026-06-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_employeemaster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_non_admin_threshold_edit',
            field=models.BooleanField(default=False, help_text='Allow non-admin staff to edit low stock threshold'),
        ),
        migrations.AddField(
            model_name='project',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Low stock threshold limit for pharmacy inventory'),
        ),
    ]
