# Generated by Django 5.2.12 on 2026-06-27 09:48

import patients.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_project_allow_non_admin_threshold_edit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, storage=patients.storage.MongoGridFSStorage(), upload_to='employee_proofs/'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, storage=patients.storage.MongoGridFSStorage(), upload_to='family_proofs/'),
        ),
    ]
