# Generated by Django 5.2.8 on 2026-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userrole_user_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="data_isolation",
            field=models.BooleanField(
                default=False,
                help_text="If True, users with this role can only see records they created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="PATIENT", max_length=50),
        ),
    ]
