# Generated by Django 5.2.8 on 2026-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userrole_data_isolation_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed module paths, e.g., ['/patients', '/vitals']",
            ),
        ),
    ]
