# Generated by Django 5.2.8 on 2026-03-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userrole_permissions"),
        ("patients", "0008_patient_registered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="patients.project",
            ),
        ),
    ]
