# Generated by Django 5.2.12 on 2026-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
