# Generated by Django 5.2.12 on 2026-06-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_project'),
        ('patients', '0036_project_allow_custom_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='patients.project'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('name', 'project')},
        ),
    ]
