# Generated by Django 5.2.12 on 2026-06-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userrole_project_alter_userrole_name_and_more'),
        ('pharmacy', '0013_facilityroom_userroomassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='pharmacy.facilityroom'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_log_dispensation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_raise_indent',
            field=models.BooleanField(default=True),
        ),
    ]
