# Generated by Django 5.2.8 on 2026-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_VITALS", "Pending Vitals"),
                    ("PENDING_CONSULTATION", "Pending Consultation"),
                    ("PENDING_LAB", "Pending Laboratory"),
                    ("PENDING_PHARMACY", "Pending Pharmacy"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING_VITALS",
                max_length=30,
            ),
        ),
    ]
