# Generated by Django 5.2.8 on 2026-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_visit_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vitals",
            options={"verbose_name_plural": "Vitals"},
        ),
        migrations.AddField(
            model_name="vitals",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="respiratory_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="spo2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
