# Generated by Django 5.2.8 on 2026-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_alter_vitals_options_vitals_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_VITALS", "Pending Vitals"),
                    ("PENDING_CONSULTATION", "Initial Consultation"),
                    ("PENDING_LAB", "Laboratory Hub"),
                    ("FINAL_CONSULTATION", "Final Prescription"),
                    ("PENDING_PHARMACY", "Pharmacy Dispensing"),
                    ("COMPLETED", "Visit Completed"),
                ],
                default="PENDING_VITALS",
                max_length=30,
            ),
        ),
    ]
