# Generated by Django 5.2.8 on 2026-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitals",
            name="alcohol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="allergy_drug",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="allergy_food",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_cancer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_cvs",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_dm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_htn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_others",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_tb",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="family_thyroid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="food_habit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_cancer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_cvs",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_dm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_htn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_others",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_tb",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="known_thyroid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="physical_activity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="smoking",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_cns",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_cvs",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_gis",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_gus",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_mss",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="sys_respiratory",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
