# Generated by Django 5.2.12 on 2026-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_vitals_alcohol_vitals_allergy_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled (Pending)'), ('CONFIRMED', 'Confirmed (Acknowledged)'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
    ]
