# Generated by Django 5.2.12 on 2026-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_appointment_end_time_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled (Pending)'), ('CONFIRMED', 'Confirmed (Acknowledged by Admin)'), ('PATIENT_ACKNOWLEDGED', 'Patient Acknowledged'), ('REJECTED', 'Rejected by Patient'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
    ]
