# Generated by Django 5.2.12 on 2026-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='history_of_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='physical_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
