# Generated by Django 5.2.12 on 2026-06-05 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_alter_consultation_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_late_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='late_entry_justification',
            field=models.CharField(blank=True, choices=[('OFFLINE_CHARTING', 'Offline/Paper Charting Reconciliation'), ('DELAYED_DOCUMENTATION', 'Delayed Administrative Documentation'), ('EMERGENCY_BACKLOG', 'Emergency Backlog Prioritization'), ('SYSTEM_DOWNTIME', 'System/Network Downtime Recovery')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='conducted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
