# Generated by Django 5.2.12 on 2026-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_visit_entered_at_visit_is_late_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reversion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
