# Generated by Django 6.0.3 on 2026-04-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0006_vitals_alcohol_vitals_allergy_drug_and_more'),
        ('patients', '0017_alter_employeemaster_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_departments', to='patients.project')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_ordered', to=settings.AUTH_USER_MODEL)),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinical.visit')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labrequest')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labdepartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.project')),
            ],
        ),
        migrations.CreateModel(
            name='LabSubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('value_type', models.CharField(choices=[('INPUT', 'Input (Numeric/Short Text)'), ('DROPDOWN', 'Dropdown Selection'), ('DESCRIPTIVE', 'Descriptive Text')], default='INPUT', max_length=20)),
                ('input_data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], default='text', max_length=20)),
                ('min_chars', models.IntegerField(blank=True, default=0, null=True)),
                ('max_chars', models.IntegerField(blank=True, default=255, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('biological_range', models.CharField(blank=True, max_length=100, null=True)),
                ('dropdown_options', models.JSONField(blank=True, default=list, help_text='List of strings for dropdown values', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tests', to='laboratory.labtestmaster')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labtestmaster'),
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_types', to='patients.project')),
            ],
        ),
        migrations.AddField(
            model_name='labtestmaster',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labtesttype'),
        ),
    ]
