# Generated by Django 6.0.3 on 2026-04-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labdepartment_is_active_labrequest_is_active_and_more'),
        ('patients', '0017_alter_employeemaster_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instrument_id', models.CharField(help_text='HL7 MSH Machine ID', max_length=100, unique=True)),
                ('port', models.IntegerField(default=9000, help_text='TCP Port to listen for data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_analyzers', to='patients.project')),
            ],
        ),
    ]
