# Generated by Django 6.0.3 on 2026-04-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labanalyzer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='laboratory.labanalyzer')),
            ],
        ),
    ]
