# Generated by Django 6.0.3 on 2026-04-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_analyzerlog'),
        ('patients', '0017_alter_employeemaster_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labanalyzer',
            name='project',
        ),
        migrations.CreateModel(
            name='LabMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=200)),
                ('lab_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('composite_identity', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='patients.project')),
            ],
            options={
                'verbose_name': 'Lab Machine Station',
                'unique_together': {('machine_id', 'machine_name', 'lab_id', 'location')},
            },
        ),
        migrations.CreateModel(
            name='LabMachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=50)),
                ('machine_name', models.CharField(max_length=100)),
                ('lab_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('sample_id', models.CharField(db_index=True, max_length=100)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('wbc', models.FloatField(blank=True, null=True)),
                ('lym_pct', models.FloatField(blank=True, null=True)),
                ('mid_pct', models.FloatField(blank=True, null=True)),
                ('gran_pct', models.FloatField(blank=True, null=True)),
                ('lym_abs', models.FloatField(blank=True, null=True)),
                ('mid_abs', models.FloatField(blank=True, null=True)),
                ('gran_abs', models.FloatField(blank=True, null=True)),
                ('rbc', models.FloatField(blank=True, null=True)),
                ('hgb', models.FloatField(blank=True, null=True)),
                ('hct', models.FloatField(blank=True, null=True)),
                ('mcv', models.FloatField(blank=True, null=True)),
                ('mch', models.FloatField(blank=True, null=True)),
                ('mchc', models.FloatField(blank=True, null=True)),
                ('rdw_cv', models.FloatField(blank=True, null=True)),
                ('rdw_sd', models.FloatField(blank=True, null=True)),
                ('plt', models.FloatField(blank=True, null=True)),
                ('mpv', models.FloatField(blank=True, null=True)),
                ('pct', models.FloatField(blank=True, null=True)),
                ('p_lcr', models.FloatField(blank=True, null=True)),
                ('p_lcc', models.FloatField(blank=True, null=True)),
                ('pdw_sd', models.FloatField(blank=True, null=True)),
                ('pdw_cv', models.FloatField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('received_at_machine', models.DateTimeField(db_index=True)),
                ('synced_at_cloud', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_results', to='patients.project')),
            ],
            options={
                'verbose_name': 'Lab Machine Raw Result',
            },
        ),
        migrations.DeleteModel(
            name='AnalyzerLog',
        ),
        migrations.DeleteModel(
            name='LabAnalyzer',
        ),
        migrations.AddIndex(
            model_name='labmachinedata',
            index=models.Index(fields=['patient_id', 'received_at_machine'], name='laboratory__patient_8fed79_idx'),
        ),
        migrations.AddIndex(
            model_name='labmachinedata',
            index=models.Index(fields=['received_at_machine', 'machine_id'], name='laboratory__receive_67d2c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labmachinedata',
            unique_together={('patient_id', 'machine_id', 'received_at_machine')},
        ),
    ]
