# Generated by Django 6.0.3 on 2026-04-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_remove_labanalyzer_project_labmachine_labmachinedata_and_more'),
        ('patients', '0017_alter_employeemaster_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmachine',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='patients.project'),
        ),
        migrations.AlterField(
            model_name='labmachinedata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_results', to='patients.project'),
        ),
    ]
