# Generated by Django 6.0.3 on 2026-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_labmachine_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachinedata',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
