# Generated by Django 6.0.3 on 2026-04-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labmachinedata_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachine',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='LabSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status_msg', models.TextField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_history', to='laboratory.labmachine')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['machine', 'received_at'], name='laboratory__machine_a1da60_idx')],
            },
        ),
    ]
