# Generated by Django 5.2.12 on 2026-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_labmachine_last_synced_at_labsyncaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachine',
            name='sync_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique API key for machine-to-cloud synchronization', max_length=100, null=True, unique=True),
        ),
    ]
