# Generated by Django 5.2.12 on 2026-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_labmachine_sync_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachine',
            name='alert_emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails for downtime alerts', null=True),
        ),
        migrations.AddField(
            model_name='labmachine',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of IPv4/IPv6 addresses authorized for this key'),
        ),
        migrations.AddField(
            model_name='labmachine',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='If true, server will send RESET command to attached agent'),
        ),
        migrations.AddField(
            model_name='labmachine',
            name='telemetry_data',
            field=models.JSONField(blank=True, default=dict, help_text='Real-time performance metrics (count, latency, etc.)'),
        ),
        migrations.AddField(
            model_name='labsyncaudit',
            name='processing_time_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
