# Generated by Django 5.2.12 on 2026-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_labmachine_alert_emails_labmachine_allowed_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachine',
            name='downtime_threshold',
            field=models.IntegerField(default=5, help_text='Send alert if no pulse for X minutes'),
        ),
    ]
