# Generated by Django 5.2.12 on 2026-04-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_labmachine_downtime_threshold'),
        ('patients', '0025_remove_project_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProjectBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of IPs allowed to sink data for this project')),
                ('alert_emails', models.TextField(blank=True, help_text='Comma-separated emails for project-wide alerts', null=True)),
                ('downtime_threshold', models.IntegerField(default=5, help_text='Global threshold for machines in this project')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bridge', to='patients.project')),
            ],
        ),
    ]
