# Generated by Django 5.2.12 on 2026-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_labprojectbridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmachinedata',
            name='alb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='alp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='amyl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='bun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='chol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='cl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='crea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='dbil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='direct_ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ggt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='glu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='hdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ibil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ldh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='phos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='sgot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='sgpt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='tbil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='tgl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='urea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='uric',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmachinedata',
            name='vldl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
