# Generated by Django 5.2.12 on 2026-06-05 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_labmachinedata_alb_labmachinedata_alp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
