# Generated by Django 5.2.12 on 2026-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_alter_labrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lab_results/attachments/'),
        ),
        migrations.AddField(
            model_name='labtestmaster',
            name='supports_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
