# Generated by Django 5.2.12 on 2026-06-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_labresult_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_results/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratory.labresult')),
            ],
        ),
    ]
