# Generated by Django 5.2.12 on 2026-05-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_group', models.CharField(max_length=100)),
                ('warehouse', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_uom', models.CharField(default='Nos', max_length=50)),
                ('balance_qty', models.IntegerField(default=0)),
                ('valuation_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispensingrecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dispensingrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dispensingrecord',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine'),
        ),
    ]
