# Generated by Django 5.2.12 on 2026-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_dispensingrecord_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='dispensingrecord',
            name='medicine',
        ),
        migrations.AlterField(
            model_name='dispensingrecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dispensingrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
