# Generated by Django 5.2.12 on 2026-05-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_registrydata_aliases_alter_project_primary_color'),
        ('pharmacy', '0005_prescription_total_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('initial_qty', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='patients.registrydata')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='dispensingrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensings', to='pharmacy.drugbatch'),
        ),
    ]
