# Generated by Django 5.2.12 on 2026-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_drugbatch_dispensingrecord_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbatch',
            name='batch_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(max_length=255),
        ),
    ]
