# Generated by Django 5.2.12 on 2026-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_drugbatch_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, default='As directed', max_length=100, null=True),
        ),
    ]
