# Generated by Django 5.2.12 on 2026-06-05 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_prescription_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingrecord',
            name='dispensed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
