# Generated by Django 5.2.12 on 2026-06-11 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_project_allow_custom_visit_date'),
        ('pharmacy', '0009_alter_dispensingrecord_dispensed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by_role', models.CharField(max_length=50)),
                ('requesting_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Doctor Approval'), ('APPROVED', 'Approved (Pending Pharmacy)'), ('DISPENSED', 'Dispensed to Room Stock'), ('REJECTED', 'Rejected by Doctor'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=20)),
                ('doctor_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indents_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='patients.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('requested_quantity', models.IntegerField()),
                ('approved_quantity', models.IntegerField(default=0)),
                ('dispensed_quantity', models.IntegerField(default=0)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.indent')),
                ('registry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indent_items', to='patients.registrydata')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_stocks', to='patients.project')),
                ('registry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_stocks', to='patients.registrydata')),
            ],
            options={
                'unique_together': {('project', 'location', 'registry_item')},
            },
        ),
        migrations.CreateModel(
            name='RoomStockDispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('PATIENT', 'Registered Patient'), ('OUTSIDE_PATIENT', 'Outside / Unregistered Patient')], default='PATIENT', max_length=20)),
                ('outside_patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('outside_patient_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('outside_patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('outside_patient_details', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_dispensations_given', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_dispensations', to='patients.patient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_dispensations', to='patients.project')),
                ('room_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='pharmacy.roomstock')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_transfers', to='pharmacy.drugbatch')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_transfers_dispensed', to=settings.AUTH_USER_MODEL)),
                ('indent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pharmacy.indentitem')),
            ],
        ),
    ]
