# Generated by Django 5.2.12 on 2026-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_indent_indentitem_roomstock_roomstockdispensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
