# Generated by Django 5.2.12 on 2026-06-27 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_prescription_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingrecord',
            name='dispensed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roomstockdispensation',
            name='dispensed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
