# Generated by Django 5.2.12 on 2026-06-29 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_alter_employeemaster_proof_image_and_more'),
        ('pharmacy', '0012_alter_dispensingrecord_dispensed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('NURSE_ROOM', 'Nurse Room'), ('LABORATORY', 'Laboratory'), ('OHC', 'Occupational Health Centre (OHC)'), ('EMERGENCY', 'Emergency Room'), ('WARD', 'General Ward'), ('OTHER', 'Other Facility')], default='NURSE_ROOM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_rooms', to='patients.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_raise_indent', models.BooleanField(default=True)),
                ('can_log_dispensation', models.BooleanField(default=True)),
                ('assigned_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to='pharmacy.facilityroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
